---
services:
  ethoscope-lab:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JUPYTER_HUB_TAG: ${JUPYTER_HUB_TAG:-5.3.0}
    image: ggilestro/ethoscope-lab:${ETHOSCOPE_LAB_TAG:-1.0}
    container_name: ethoscope-lab
    ports:
      - 8082:8000
    volumes:
      - /mnt/data/results:/mnt/ethoscope_results:ro
      - /mnt/data/ethoscope_metadata:/opt/ethoscope_metadata
      - /mnt/homes:/home
      - /mnt/cache:/home/cache
      - ./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro
    user: "gg:users" # Make sure this matches the permissions of your /mnt/{homes,cache} folder
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]